sudo: required
dist: trusty
language: python
python:
  - "3.5"
install:
  - sudo apt remove swig
  - sudo apt install swig3.0
  - sudo ln -s /usr/bin/swig3.0 /usr/bin/swig
  - sudo apt install portaudio19-dev libatlas-dev libatlas-base-dev pulseaudio libpulse-dev unzip python3-setuptools python3-pip sox
  - ./.travis_scripts/install.sh
  - pip3 install -U pytest
script:
  - python3 -m pytest tests/
